rewrote __str__ and __repr__ + test for them
Jerikho7/electronics-shop-project pull request #3
Opened 2023-11-09 07:36 UTC by Jerikho7

2023-11-09 15:40 UTC, painassasin requested changes

2023-11-09 15:40 UTC, painassasin commented on tests/test_item.py
> +    assert repr(item_for_test) == "Item('Television', 150000.0, 5)" #не могу понять почему float а не int
Потому что `item_for_test` - это глобальная переменная, которая изменяется во время тестов, а должна быть фикстура:
```python
@pytest.fixture()
def item_for_test():
   return  Item("Television", 150000, 5)


def test_repr(item_for_test):
    assert repr(item_for_test) == "Item('Television', 150000, 5)"
```
В остальных тестах тоже измени на использование фикстуры и удали переменные из глобальной области видимости

2023-11-09 15:40 UTC, painassasin commented on src/item.py
> +        return f'{self.__name}'
Тут не нужно использовать f-строку

2023-11-10 03:15 UTC, Jerikho7 commented on src/item.py
> +        return f'{self.__name}'
Когда попробовала убрать строку сразу вылезла ошибка при тесте ( TypeError: __str__ returned non-string (type set)) поэтому в __str__ оставила ее

2023-11-10 07:42 UTC, painassasin approved these changes

2023-11-10 07:42 UTC, painassasin commented on tests/test_item.py
> +    assert repr(item_for_test) == "Item('Television', 150000, 5)"  # не могу понять почему float а не int
Коммент можно убрать

2023-11-10 07:43 UTC, painassasin commented on src/item.py
> +        return f'{self.__name}'
Тут вероятнее всего значит ошибка в тесте - судя по всему у тебя должна быть там строка в любом случае

2023-11-10 09:01 UTC, merged